name: Build K2P-nano

on: 
  workflow_dispatch: # 手动触发
#  watch:
#    types: [started]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        sudo chmod 777 /opt/rt-n56u
    - name: Run shellcheck
      run: sh /opt/rt-n56u/trunk/tools/shellcheck.sh
    - name: Prepare toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        mkdir -p /opt/images/
        sudo ./clear_tree_simple
        fakeroot ./build_firmware_ci K2P_nano
        sudo mv -f images/*.trx /opt/images/
        done
    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
